mybatis:
  config-location: classpath:/mybatis/mybatis-config.xml

file:
  path: /User/luo/imgs
  prefix: http:127.0.0.1:8080/imgs
domain:
  name: 127.0.0.1:8080
spring:
  druid:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1/fcsale?serverTimezone=UTC&characterEncoding=utf-8&userSSL=false
    username: root
    password: 123
    maxActive: 30
    minIdle: 5
    maxWait: 20000
    validationQuery: SELECT 'x'
    timeBetweenEvictionRunsMillis: 600000
    minEvictableIdleTimeMillis: 300000

  mail:
    host: smtp.qq.com
    username: 2084267015@qq.com
    password: frxmhgwvlcurdfgf
    properties:
      mail:
        smtp:
          auth: true
          starttles:
            enable: true
            required: true
  boot:
    admin:
      url: http://127.0.0.1:8083 # 监控平台
management:
  port: 8082 # 只给内部系统访问的 actuator信息,endpoint 端口号

